language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install requests
  - pip install coverage
  - pip install coveralls
# command to run tests
script:
  - coverage run -m unittest discover 'test' 'test*.py'
# coverage
after_success:
  coveralls
